micronaut:
  application:
    name: 'Key Manager Grpc Test'

datasources:
  default:
    url: jdbc:h2:mem:test;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update

itau-erp.url: ${ITAU_ERP_URL:`http://localhost:9091/`}